###############################
# server setting
###############################
server:
  port: 28080

spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

pg:
  default: KG_MOBILIANS
  kgmobilians:
    merchant-id: test_merchant
    api-key: test_apikey
    payment-url: https://kgmobilians.example.com/pay
  paywill:
    client-id: pw_client
    client-secret: pw_secret
    payment-url: https://paywill.example.com/pay

###############################
# profiles environment setting
###############################
--- #local
spring:
  config:
    activate:
      on-profile: local

pg:
  default: MOCK

