###############################
# server setting
###############################
server:
  port: 28080

spring:
  # profiles
  profiles:
    default: local
  # html view 사용
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

pg:
  default: KG_MOBILIANS
  kg-mobilians:
    merchant-id: test_merchant
    api-key: test_apikey
  paywill:
    client-id: pw_client
    client-secret: pw_secret
  http:
    hostname: http://localhost:28080
    common:
      auth:
        header:
          apikey:
            name: secretKey
          transaction:
            name: trstNo
      timeout: 5
      retry:
        count: 5


###############################
# profiles environment setting
###############################
--- #local
spring:
  config:
    activate:
      on-profile: local

pg:
  default: MOCK
  kg-mobilians:
    payment-url: https://test.mobilians.co.kr
  paywill:
    payment-url: https://paywill.example.com/pay


--- #dev
spring:
  config:
    activate:
      on-profile: dev

pg:
  kg-mobilians:
    payment-url: https://test.mobilians.co.kr
  paywill:
    payment-url: https://paywill.example.com/pay


--- #prod
spring:
  config:
    activate:
      on-profile: prod

pg:
  kg-mobilians:
    payment-url: https://mup.mobilians.co.k
  paywill:
    payment-url: https://paywill.example.com/pay
